# Generated by Django 4.2 on 2024-10-12 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('latitude_direction', models.CharField(max_length=1)),
                ('longitude', models.FloatField()),
                ('longitude_direction', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=30)),
                ('viewing_radius', models.IntegerField(default=10)),
                ('peak_time', models.DateTimeField(default=datetime.datetime(2024, 10, 12, 20, 37, 43, 79920, tzinfo=datetime.timezone.utc))),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars_app.location')),
            ],
        ),
    ]
