# Generated by Django 5.1.3 on 2025-10-17 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("stars_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviewvote",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="reviewvote",
            name="review",
        ),
        migrations.RemoveField(
            model_name="reviewvote",
            name="user",
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the specific object being voted on"
                    ),
                ),
                (
                    "is_upvote",
                    models.BooleanField(
                        help_text="True for upvote, False for downvote"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The type of object being voted on (e.g., LocationReview, ReviewComment, etc.)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who cast this vote",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="CommentVote",
        ),
        migrations.DeleteModel(
            name="ReviewVote",
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="stars_app_v_content_9f8453_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["user", "-created_at"], name="stars_app_v_user_id_95aac8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
