# Generated by Django 4.2 on 2024-10-12 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='peak_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 20, 59, 16, 983191, tzinfo=datetime.timezone.utc)),
        ),
    ]
