# Generated by Django 5.1.3 on 2024-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewinglocation',
            name='elevation',
            field=models.FloatField(blank=True, help_text='Elevation in meters', null=True),
        ),
    ]
