# Generated by Django 5.1.3 on 2024-12-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0002_alter_viewinglocation_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewinglocation',
            name='elevation',
            field=models.FloatField(default=0, help_text='Elevation in meters'),
        ),
    ]
