# Generated by Django 5.1.13 on 2025-10-17 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("stars_app", "0002_alter_reviewvote_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ViewingLocation",
            new_name="Location",
        ),
        migrations.RenameModel(
            old_name="LocationReview",
            new_name="Review",
        ),
        migrations.AlterField(
            model_name="report",
            name="content_type",
            field=models.ForeignKey(
                help_text="The type of object being reported (e.g., Location, Review, etc.)",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="content_type",
            field=models.ForeignKey(
                help_text="The type of object being voted on (e.g., Review, ReviewComment, etc.)",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
