# Generated by Django 5.1.3 on 2025-06-14 09:34

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0003_add_more_missing_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinglocation',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this location has been verified'),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, help_text='When the location was verified'),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_locations', to=settings.AUTH_USER_MODEL, help_text='User who verified this location'),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes about the verification process'),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='times_reported',
            field=models.IntegerField(default=0, help_text='Number of times this location has been reported'),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='last_visited',
            field=models.DateTimeField(blank=True, null=True, help_text='Last time someone reported visiting this location'),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='visitor_count',
            field=models.IntegerField(default=0, help_text='Number of unique visitors who have reviewed this location'),
        ),
    ]
