# Generated by Django 5.1.13 on 2025-10-20 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("stars_app", "0003_rename_viewinglocation_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="formatted_address",
            field=models.CharField(
                blank=True,
                help_text="Full formatted address from geocoding",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether this location has been verified by staff",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="verification_notes",
            field=models.TextField(
                blank=True, help_text="Staff notes about the verification process"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who verified this location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="additional_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional JSON for additional context",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="content_type",
            field=models.ForeignKey(
                help_text="Type of object being reported",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of the issue"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="object_id",
            field=models.PositiveIntegerField(
                help_text="ID of the specific object being reported"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("SPAM", "Spam or Low Quality"),
                    ("HARASSMENT", "Harassment or Bullying"),
                    ("INAPPROPRIATE", "Inappropriate Content"),
                    ("MISINFORMATION", "False or Misleading Information"),
                    ("DUPLICATE", "Duplicate Location"),
                    ("INACCURATE", "Inaccurate Information"),
                    ("CLOSED", "Location Closed/Inaccessible"),
                    ("DANGEROUS", "Safety Concerns"),
                    ("OTHER", "Other"),
                ],
                help_text="Type/reason for this report",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_by",
            field=models.ForeignKey(
                help_text="User who submitted this report",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="review_notes",
            field=models.TextField(blank=True, help_text="Internal moderator notes"),
        ),
        migrations.AlterField(
            model_name="report",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When this report was reviewed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator who reviewed this report",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("REVIEWED", "Reviewed"),
                    ("RESOLVED", "Resolved"),
                    ("DISMISSED", "Dismissed"),
                ],
                default="PENDING",
                help_text="Current status in moderation workflow",
                max_length=20,
            ),
        ),
    ]
