# Generated by Django 4.2 on 2024-10-27 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stars_app', '0003_alter_event_peak_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('METEOR', 'Meteor Shower'), ('ECLIPSE', 'Eclipse'), ('PLANET', 'Planetary Event'), ('AURORA', 'Aurora'), ('OTHER', 'Other')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('viewing_radius', models.FloatField(help_text='Optimal viewing radius in km')),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.FloatField(help_text='Calculated viewing quality score (0-100)')),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars_app.celestialevent')),
            ],
            options={
                'ordering': ['quality_score'],
            },
        ),
        migrations.CreateModel(
            name='ViewingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField(help_text='Elevation in meters')),
                ('light_pollution_value', models.FloatField(blank=True, help_text='Calculated light pollution value from tiles', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars_app.viewinglocation'),
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='recommended_locations',
            field=models.ManyToManyField(blank=True, through='stars_app.EventLocation', to='stars_app.viewinglocation'),
        ),
    ]
