# Generated by Django 5.1.13 on 2025-10-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0004_alter_location_formatted_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="helpful_reviews_count",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_trusted_contributor",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="quality_photos_count",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="reputation_score",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="verified_locations_count",
        ),
    ]
