# Generated by Django 5.1.3 on 2025-06-14 09:41

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import stars_app.models.locationphoto


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0004_add_verification_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Photo of the viewing location', upload_to=stars_app.models.locationphoto.location_photo_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary photo shown in location listings')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the photo has been approved by moderators')),
                ('taken_at', models.DateTimeField(blank=True, help_text='When the photo was taken (from EXIF)', null=True)),
                ('camera_make', models.CharField(blank=True, max_length=100)),
                ('camera_model', models.CharField(blank=True, max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stars_app.viewinglocation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [
                    models.Index(fields=['location', '-created_at'], name='stars_app_l_locatio_c9b93f_idx'),
                    models.Index(fields=['uploaded_by', '-created_at'], name='stars_app_l_uploade_1b5c5a_idx'),
                    models.Index(fields=['is_approved', 'is_primary'], name='stars_app_l_is_appr_8e7c4a_idx'),
                ],
            },
        ),
    ]
