# Generated by Django 4.2 on 2024-10-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0005_alter_eventlocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celestialevent',
            name='recommended_locations',
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stars_app.viewinglocation'),
            preserve_default=False,
        ),
    ]
