# Generated by Django 5.1.3 on 2025-06-14 09:45

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0005_add_location_photos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name', unique=True)),
                ('category_type', models.CharField(choices=[('PARK', 'National/State Park'), ('MOUNTAIN', 'Mountain/Peak'), ('DESERT', 'Desert'), ('BEACH', 'Beach/Coast'), ('OBSERVATORY', 'Observatory'), ('RURAL', 'Rural Area'), ('SUBURBAN', 'Suburban Area'), ('CAMPGROUND', 'Campground'), ('FIELD', 'Open Field'), ('LAKE', 'Lake/Reservoir'), ('OTHER', 'Other')], help_text='Type of category', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('icon', models.CharField(blank=True, help_text='Icon name or class for UI', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Location Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name', unique=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of locations using this tag')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this tag has been approved by moderators')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
                'indexes': [
                    models.Index(fields=['is_approved', '-usage_count'], name='stars_app_l_is_appr_36f7a8_idx'),
                    models.Index(fields=['slug'], name='stars_app_l_slug_d8c5f5_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this location belongs to', related_name='locations', to='stars_app.locationcategory'),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this location', related_name='locations', to='stars_app.locationtag'),
        ),
    ]
