# Generated by Django 5.1.13 on 2025-10-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0005_remove_userprofile_helpful_reviews_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="quality_score_idx",
        ),
        migrations.RemoveField(
            model_name="location",
            name="quality_score",
        ),
    ]
