# Generated by Django 5.1.3 on 2024-12-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0005_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinglocation',
            name='moon_altitude',
            field=models.FloatField(blank=True, help_text="Moon's altitude above horizon in degrees", null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='moon_impact_score',
            field=models.FloatField(blank=True, help_text="Score indicating moon's impact on viewing conditions (0-1)", null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='moon_phase',
            field=models.FloatField(blank=True, help_text='Current moon phase percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='next_moonrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='next_moonset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
