# Generated by Django 5.1.3 on 2024-12-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0006_viewinglocation_moon_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinglocation',
            name='next_astronomical_dawn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='next_astronomical_dusk',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
