# Generated by Django 5.1.13 on 2025-10-28 01:22

import stars_app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0006_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='elevation',
            field=models.FloatField(default=0, help_text='Elevation in meters', validators=[stars_app.utils.validators.validate_elevation]),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(validators=[stars_app.utils.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(validators=[stars_app.utils.validators.validate_longitude]),
        ),
    ]
