# Generated by Django 5.1.3 on 2025-06-14 09:47

from django.db import migrations
from django.utils.text import slugify


def populate_default_categories(apps, schema_editor):
    LocationCategory = apps.get_model('stars_app', 'LocationCategory')
    
    default_categories = [
        {'name': 'National/State Park', 'category_type': 'PARK', 'icon': '🏞️'},
        {'name': 'Mountain/Peak', 'category_type': 'MOUNTAIN', 'icon': '⛰️'},
        {'name': 'Desert', 'category_type': 'DESERT', 'icon': '🏜️'},
        {'name': 'Beach/Coast', 'category_type': 'BEACH', 'icon': '🏖️'},
        {'name': 'Observatory', 'category_type': 'OBSERVATORY', 'icon': '🔭'},
        {'name': 'Rural Area', 'category_type': 'RURAL', 'icon': '🌾'},
        {'name': 'Suburban Area', 'category_type': 'SUBURBAN', 'icon': '🏘️'},
        {'name': 'Campground', 'category_type': 'CAMPGROUND', 'icon': '🏕️'},
        {'name': 'Open Field', 'category_type': 'FIELD', 'icon': '🌿'},
        {'name': 'Lake/Reservoir', 'category_type': 'LAKE', 'icon': '🏞️'},
        {'name': 'Other', 'category_type': 'OTHER', 'icon': '📍'},
    ]
    
    for cat_data in default_categories:
        LocationCategory.objects.create(
            name=cat_data['name'],
            slug=slugify(cat_data['name']),
            category_type=cat_data['category_type'],
            icon=cat_data['icon'],
            description=f"Viewing locations in {cat_data['name'].lower()}"
        )


def reverse_populate_categories(apps, schema_editor):
    LocationCategory = apps.get_model('stars_app', 'LocationCategory')
    LocationCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0006_add_categories_tags"),
    ]

    operations = [
        migrations.RunPython(populate_default_categories, reverse_populate_categories),
    ]
