# Generated by Django 4.2 on 2024-10-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0006_remove_celestialevent_recommended_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialevent',
            name='event_type',
            field=models.CharField(choices=[('METEOR', 'Meteor Shower'), ('ECLIPSE', 'Eclipse'), ('PLANET', 'Planetary Event'), ('AURORA', 'Aurora'), ('OTHER', 'Other'), ('COMET', 'Comet')], max_length=10),
        ),
    ]
