# Generated by Django 4.2 on 2024-10-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0007_alter_celestialevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celestialevent',
            name='location',
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='elevation',
            field=models.FloatField(default=0, help_text='Elevation in meters'),
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='EventLocation',
        ),
    ]
