# Generated by Django 5.1.13 on 2025-10-28 05:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0007_alter_location_elevation_alter_location_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked (Account Lockout)'), ('logout', 'Logout'), ('registration_success', 'Registration Success'), ('registration_failed', 'Registration Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_changed', 'Password Changed'), ('location_verified', 'Location Verified'), ('location_unverified', 'Location Unverified'), ('content_moderated', 'Content Moderated'), ('permission_denied', 'Permission Denied'), ('access_forbidden', 'Access Forbidden')], db_index=True, help_text='Type of security event', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the event occurred')),
                ('success', models.BooleanField(default=True, help_text='Whether the action succeeded or failed')),
                ('message', models.TextField(help_text='Human-readable description of the event')),
                ('username', models.CharField(blank=True, db_index=True, help_text="Username attempted (for failed logins when user doesn't exist)", max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address where the request originated', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data (JSON format)')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous or deleted users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='stars_app_a_timesta_b57615_idx'), models.Index(fields=['user', '-timestamp'], name='stars_app_a_user_id_2da393_idx'), models.Index(fields=['ip_address', '-timestamp'], name='stars_app_a_ip_addr_67cb6b_idx')],
            },
        ),
    ]
