# Generated by Django 5.1.3 on 2025-06-14 09:49

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0007_populate_default_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('DUPLICATE', 'Duplicate Location'), ('INACCURATE', 'Inaccurate Information'), ('SPAM', 'Spam or Inappropriate'), ('CLOSED', 'Location Closed/Inaccessible'), ('DANGEROUS', 'Safety Concerns'), ('OTHER', 'Other')], help_text='Type of report', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', help_text='Current status of the report', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the moderator review')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the report was reviewed', null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='If duplicate, which location is this a duplicate of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reports', to='stars_app.viewinglocation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stars_app.viewinglocation')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Moderator who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['location', 'status'], name='stars_app_l_locatio_d7e8f5_idx'),
                    models.Index(fields=['reported_by', '-created_at'], name='stars_app_l_reporte_4a8b6c_idx'),
                    models.Index(fields=['status', '-created_at'], name='stars_app_l_status_8c7d3e_idx'),
                ],
                'unique_together': {('location', 'reported_by', 'report_type')},
            },
        ),
    ]
