# Generated by Django 5.1.3 on 2025-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0008_add_location_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reputation_score',
            field=models.IntegerField(default=0, help_text="User's reputation score based on contributions"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_locations_count',
            field=models.IntegerField(default=0, help_text='Number of locations verified by this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='helpful_reviews_count',
            field=models.IntegerField(default=0, help_text='Number of helpful reviews (based on votes)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quality_photos_count',
            field=models.IntegerField(default=0, help_text='Number of approved photos uploaded'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_trusted_contributor',
            field=models.BooleanField(default=False, help_text='Whether user is a trusted contributor'),
        ),
    ]
