# Generated by Django 5.1.3 on 2025-06-14 14:23

from django.db import migrations
from django.utils import timezone


def populate_null_created_at(apps, schema_editor):
    """
    Populate NULL created_at values with current timestamp or updated_at value
    """
    CelestialEvent = apps.get_model('stars_app', 'CelestialEvent')
    UserProfile = apps.get_model('stars_app', 'UserProfile')
    
    # Fix CelestialEvent records with NULL created_at
    null_events = CelestialEvent.objects.filter(created_at__isnull=True)
    for event in null_events:
        # Use updated_at if available, otherwise current time
        event.created_at = event.updated_at or timezone.now()
        event.save()
    
    # Fix UserProfile records with NULL created_at
    null_profiles = UserProfile.objects.filter(created_at__isnull=True)
    for profile in null_profiles:
        # Use updated_at if available, otherwise current time
        profile.created_at = profile.updated_at or timezone.now()
        profile.save()


def reverse_populate_null_created_at(apps, schema_editor):
    """
    Reverse migration - set created_at back to NULL for affected records
    """
    pass  # Cannot reliably reverse this operation


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0009_add_user_reputation"),
    ]

    operations = [
        migrations.RunPython(
            populate_null_created_at,
            reverse_populate_null_created_at,
        ),
    ]
