# Generated by Django 5.1.3 on 2025-06-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0010_auto_20250614_1423"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="locationphoto",
            new_name="stars_app_l_locatio_b40753_idx",
            old_name="stars_app_l_locatio_c9b93f_idx",
        ),
        migrations.RenameIndex(
            model_name="locationphoto",
            new_name="stars_app_l_uploade_1f63ab_idx",
            old_name="stars_app_l_uploade_1b5c5a_idx",
        ),
        migrations.RenameIndex(
            model_name="locationphoto",
            new_name="stars_app_l_is_appr_a196f4_idx",
            old_name="stars_app_l_is_appr_8e7c4a_idx",
        ),
        migrations.RenameIndex(
            model_name="locationreport",
            new_name="stars_app_l_locatio_e0ce8e_idx",
            old_name="stars_app_l_locatio_d7e8f5_idx",
        ),
        migrations.RenameIndex(
            model_name="locationreport",
            new_name="stars_app_l_reporte_f081c9_idx",
            old_name="stars_app_l_reporte_4a8b6c_idx",
        ),
        migrations.RenameIndex(
            model_name="locationreport",
            new_name="stars_app_l_status_ce0079_idx",
            old_name="stars_app_l_status_8c7d3e_idx",
        ),
        migrations.RenameIndex(
            model_name="locationtag",
            new_name="stars_app_l_is_appr_e2c7bf_idx",
            old_name="stars_app_l_is_appr_36f7a8_idx",
        ),
        migrations.RenameIndex(
            model_name="locationtag",
            new_name="stars_app_l_slug_649721_idx",
            old_name="stars_app_l_slug_d8c5f5_idx",
        ),
    ]
