# Generated by Django 4.2 on 2024-11-09 20:32

from django.db import migrations, models
import django.db.models.deletion
import stars_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0010_favoritelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('forecast', models.JSONField(default=list, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='cloudCoverPercentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='forecast',
            field=models.ForeignKey(default=stars_app.models.defaultforecast, on_delete=django.db.models.deletion.CASCADE, to='stars_app.forecast'),
        ),
    ]
