# Generated by Django 5.1.3 on 2025-06-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stars_app",
            "0011_rename_stars_app_l_locatio_c9b93f_idx_stars_app_l_locatio_b40753_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="locationphoto",
            name="camera_settings",
            field=models.JSONField(
                blank=True,
                help_text="Camera settings (ISO, aperture, shutter speed, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="locationphoto",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail version of the photo",
                null=True,
                upload_to='location_photos/thumbnails',
            ),
        ),
    ]
