# Generated by Django 4.2 on 2024-11-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics/'),
        ),
    ]
