# Generated by Django 5.1.3 on 2025-06-21 22:38

import django.db.models.deletion
import stars_app.models.reviewphoto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0013_commentvote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Photo for the review",
                        upload_to=stars_app.models.reviewphoto.review_photo_path,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail version of the photo",
                        null=True,
                        upload_to=stars_app.models.reviewphoto.review_thumbnail_path,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the photo",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of display (lower numbers appear first)",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="stars_app.locationreview",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["review", "order"],
                        name="stars_app_r_review__a0dcdf_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="stars_app_r_created_3de159_idx"
                    ),
                ],
            },
        ),
    ]
