# Generated by Django 5.1.3 on 2025-06-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0014_reviewphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
