# Generated by Django 4.2 on 2024-11-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0014_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelocation',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
