# Generated by Django 5.1.3 on 2025-06-22 06:40

from django.db import migrations
from django.db.models import F


def fix_existing_comment_timestamps(apps, schema_editor):
    """Set updated_at = created_at for all existing comments to prevent false 'edited' indicators"""
    ReviewComment = apps.get_model('stars_app', 'ReviewComment')
    ReviewComment.objects.update(updated_at=F('created_at'))


def reverse_fix_existing_comment_timestamps(apps, schema_editor):
    """No reverse operation needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0015_add_updated_at_to_reviewcomment"),
    ]

    operations = [
        migrations.RunPython(
            fix_existing_comment_timestamps,
            reverse_fix_existing_comment_timestamps,
        ),
    ]
