# Generated by Django 5.1.3 on 2024-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0016_alter_viewinglocation_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinglocation',
            name='administrative_area',
            field=models.CharField(blank=True, help_text='State/Province/Region', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Full formatted address from geocoding or user input', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='viewinglocation',
            name='locality',
            field=models.CharField(blank=True, help_text='City/Town', max_length=200, null=True),
        ),
    ]
