# Generated by Django 5.1.3 on 2025-06-22 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0016_fix_existing_comment_timestamps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam or Low Quality"),
                            ("HARASSMENT", "Harassment or Bullying"),
                            ("INAPPROPRIATE", "Inappropriate Content"),
                            ("MISINFORMATION", "False or Misleading Information"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of report",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of the issue",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("REVIEWED", "Reviewed"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="PENDING",
                        help_text="Current status of the report",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the moderator review"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was reviewed", null=True
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="stars_app.reviewcomment",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who reviewed this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_comment_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["comment", "status"],
                        name="stars_app_c_comment_cd4a69_idx",
                    ),
                    models.Index(
                        fields=["reported_by", "-created_at"],
                        name="stars_app_c_reporte_5075a5_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="stars_app_c_status_a8154f_idx",
                    ),
                    models.Index(
                        fields=["report_type", "-created_at"],
                        name="stars_app_c_report__20754e_idx",
                    ),
                ],
                "unique_together": {("comment", "reported_by")},
            },
        ),
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam or Low Quality"),
                            ("HARASSMENT", "Harassment or Bullying"),
                            ("INAPPROPRIATE", "Inappropriate Content"),
                            ("MISINFORMATION", "False or Misleading Information"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of report",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of the issue",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("REVIEWED", "Reviewed"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="PENDING",
                        help_text="Current status of the report",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the moderator review"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was reviewed", null=True
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="stars_app.locationreview",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who reviewed this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_review_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["review", "status"],
                        name="stars_app_r_review__005246_idx",
                    ),
                    models.Index(
                        fields=["reported_by", "-created_at"],
                        name="stars_app_r_reporte_087d6d_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="stars_app_r_status_5f6d89_idx",
                    ),
                    models.Index(
                        fields=["report_type", "-created_at"],
                        name="stars_app_r_report__30aefe_idx",
                    ),
                ],
                "unique_together": {("review", "reported_by")},
            },
        ),
    ]
