# Generated by Django 5.1.3 on 2024-12-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars_app', '0017_viewinglocation_administrative_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewinglocation',
            name='light_pollution_value',
            field=models.FloatField(blank=True, help_text='Light pollution in magnitude per square arcsecond (higher values = darker skies)', null=True),
        ),
        migrations.AlterField(
            model_name='viewinglocation',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Overall viewing quality score (0-100) based on light pollution and elevation', null=True),
        ),
    ]
