# Generated by Django 5.1.3 on 2025-10-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stars_app", "0017_commentreport_reviewreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CelestialEvent",
        ),
    ]
