# Generated by Django 5.1.13 on 2025-11-09 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address that bounced', max_length=254)),
                ('bounce_type', models.CharField(choices=[('hard', 'Hard Bounce (Permanent)'), ('soft', 'Soft Bounce (Temporary)'), ('transient', 'Transient (Connection Issue)')], db_index=True, help_text='Type of bounce (hard/soft/transient)', max_length=20)),
                ('bounce_subtype', models.CharField(choices=[('undetermined', 'Undetermined'), ('general', 'General'), ('no_email', 'Mailbox Does Not Exist'), ('suppressed', 'Address Suppressed'), ('mailbox_full', 'Mailbox Full'), ('message_too_large', 'Message Too Large'), ('content_rejected', 'Content Rejected'), ('attachment_rejected', 'Attachment Rejected')], default='undetermined', help_text='Specific reason for bounce', max_length=50)),
                ('bounce_count', models.PositiveIntegerField(default=1, help_text='Number of times this email has bounced')),
                ('first_bounce_date', models.DateTimeField(auto_now_add=True, help_text='First time this email bounced')),
                ('last_bounce_date', models.DateTimeField(auto_now=True, help_text='Most recent bounce')),
                ('sns_message_id', models.CharField(help_text='AWS SNS message ID for deduplication', max_length=255, unique=True)),
                ('diagnostic_code', models.TextField(blank=True, help_text='SMTP diagnostic message from receiving server')),
                ('raw_notification', models.JSONField(help_text='Complete SNS notification payload')),
                ('suppressed', models.BooleanField(db_index=True, default=False, help_text='Whether this email has been added to suppression list')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this email (if exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_bounces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Bounce',
                'verbose_name_plural': 'Email Bounces',
                'db_table': 'starview_email_bounce',
                'ordering': ['-last_bounce_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address that complained', max_length=254)),
                ('complaint_type', models.CharField(choices=[('abuse', 'Abuse Report'), ('auth-failure', 'Authentication Failure'), ('fraud', 'Fraud Report'), ('not-spam', 'Not Spam (False Positive)'), ('other', 'Other/Unknown'), ('virus', 'Virus Report')], default='other', help_text='Type of complaint reported', max_length=50)),
                ('user_agent', models.CharField(blank=True, help_text='Email client user agent (if available)', max_length=255)),
                ('complaint_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the complaint was received')),
                ('sns_message_id', models.CharField(help_text='AWS SNS message ID for deduplication', max_length=255, unique=True)),
                ('feedback_id', models.CharField(blank=True, help_text='Feedback loop identifier from ISP', max_length=255)),
                ('raw_notification', models.JSONField(help_text='Complete SNS notification payload')),
                ('suppressed', models.BooleanField(db_index=True, default=False, help_text='Whether this email has been added to suppression list')),
                ('reviewed', models.BooleanField(default=False, help_text='Whether admin has reviewed this complaint')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this email (if exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Complaint',
                'verbose_name_plural': 'Email Complaints',
                'db_table': 'starview_email_complaint',
                'ordering': ['-complaint_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailSuppressionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address to suppress', max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard Bounce (Permanent Failure)'), ('soft_bounce', 'Soft Bounce (Multiple Failures)'), ('complaint', 'Spam Complaint'), ('manual', 'Manual Addition (Admin)'), ('unsubscribe', 'User Unsubscribed')], help_text='Why this email was suppressed', max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this email was added to suppression list')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether suppression is currently active')),
                ('bounce', models.ForeignKey(blank=True, help_text='Related bounce record (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='starview_app.emailbounce')),
                ('complaint', models.ForeignKey(blank=True, help_text='Related complaint record (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='starview_app.emailcomplaint')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this email (if exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_suppressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppression List',
                'db_table': 'starview_email_suppression',
                'ordering': ['-added_date'],
            },
        ),
        migrations.AddIndex(
            model_name='emailbounce',
            index=models.Index(fields=['email', '-last_bounce_date'], name='starview_em_email_a87f61_idx'),
        ),
        migrations.AddIndex(
            model_name='emailbounce',
            index=models.Index(fields=['bounce_type', 'suppressed'], name='starview_em_bounce__2bc32e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcomplaint',
            index=models.Index(fields=['email', '-complaint_date'], name='starview_em_email_5bcb32_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcomplaint',
            index=models.Index(fields=['reviewed', 'suppressed'], name='starview_em_reviewe_dc477e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuppressionlist',
            index=models.Index(fields=['email', 'is_active'], name='starview_em_email_49c712_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuppressionlist',
            index=models.Index(fields=['reason', 'added_date'], name='starview_em_reason_9c0f3f_idx'),
        ),
    ]
