# Generated by Django 5.1.13 on 2025-11-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0002_email_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short bio visible on public profile (max 500 characters)', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', help_text="User's location (e.g., 'Seattle, WA')", max_length=100),
        ),
    ]
