# Generated by Django 5.1.13 on 2025-11-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0003_add_bio_and_location_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified badge status for user profile'),
        ),
    ]
