# Generated by Django 5.1.13 on 2025-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0004_userprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short bio visible on public profile (max 150 characters)', max_length=150),
        ),
    ]
