# Generated by Django 5.1.13 on 2025-11-11 23:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0006_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pinned_badge_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Up to 3 badge IDs to display on profile header', size=3),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EXPLORATION', 'Exploration'), ('CONTRIBUTION', 'Contribution'), ('QUALITY', 'Quality'), ('REVIEW', 'Review'), ('COMMUNITY', 'Community'), ('TENURE', 'Time-Based'), ('SPECIAL', 'Special/Rare')], max_length=20)),
                ('criteria_type', models.CharField(choices=[('LOCATION_VISITS', 'Location Visits'), ('LOCATIONS_ADDED', 'Locations Added'), ('LOCATION_RATING', 'Location Quality Rating'), ('REVIEWS_WRITTEN', 'Reviews Written'), ('UPVOTES_RECEIVED', 'Upvotes Received'), ('HELPFUL_RATIO', 'Helpful Review Ratio'), ('COMMENTS_WRITTEN', 'Comments Written'), ('FOLLOWER_COUNT', 'Follower Count'), ('TENURE_DAYS', 'Days as Member'), ('SPECIAL_CONDITION', 'Special Condition')], max_length=30)),
                ('criteria_value', models.IntegerField()),
                ('criteria_secondary', models.IntegerField(blank=True, null=True)),
                ('tier', models.SmallIntegerField(default=1)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('is_rare', models.BooleanField(default=False)),
                ('icon_path', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'tier', 'display_order'],
                'indexes': [models.Index(fields=['category', 'criteria_type'], name='starview_ap_categor_373dbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='starview_app.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['user', 'visited_at'], name='starview_ap_user_id_54bc53_idx')],
                'unique_together': {('user', 'location')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starview_app.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'earned_at'], name='starview_ap_user_id_a71584_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
