# Generated by Django 5.1.13 on 2025-11-12 00:30

from django.db import migrations


def seed_badges(apps, schema_editor):
    """
    Seed initial badge definitions for the Starview badge system.

    Creates 20 core badges across 5 categories:
    - Exploration (6 badges) - Location visit count
    - Contribution (4 badges) - Location creation count
    - Review (5 badges) - Review writing count
    - Community (4 badges) - Follower and comment count
    - Special (1 badge) - Photographer achievement

    Quality, Tenure, and advanced Special badges will be added in Phase 2.
    """
    Badge = apps.get_model('starview_app', 'Badge')

    badges_to_create = [
        # ===================================================================
        # EXPLORATION BADGES (Location Visits)
        # ===================================================================
        {
            'name': 'First Light',
            'slug': 'first-light',
            'description': 'Visit your first stargazing location',
            'category': 'EXPLORATION',
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 1,
            'tier': 1,
            'color': 'bronze',
            'is_rare': False,
            'icon_path': '/badges/first-light.png',
            'display_order': 1,
        },
        {
            'name': 'Explorer',
            'slug': 'explorer',
            'description': 'Begin your stargazing journey - visit 5 locations',
            'category': 'EXPLORATION',
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 5,
            'tier': 2,
            'color': 'bronze',
            'is_rare': False,
            'icon_path': '/badges/explorer.png',
            'display_order': 2,
        },
        {
            'name': 'Pathfinder',
            'slug': 'pathfinder',
            'description': 'Navigate the night sky - visit 10 locations',
            'category': 'EXPLORATION',
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 10,
            'tier': 3,
            'color': 'silver',
            'is_rare': False,
            'icon_path': '/badges/pathfinder.png',
            'display_order': 3,
        },
        {
            'name': 'Stargazer',
            'slug': 'stargazer',
            'description': 'Dedicated night sky observer - visit 25 locations',
            'category': 'EXPLORATION',
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 25,
            'tier': 4,
            'color': 'gold',
            'is_rare': False,
            'icon_path': '/badges/stargazer.png',
            'display_order': 4,
        },
        {
            'name': 'Celestial Navigator',
            'slug': 'celestial-navigator',
            'description': 'Master of dark skies - visit 50 locations',
            'category': 'EXPLORATION',
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 50,
            'tier': 5,
            'color': 'platinum',
            'is_rare': False,
            'icon_path': '/badges/celestial-navigator.png',
            'display_order': 5,
        },
        {
            'name': 'Cosmic Voyager',
            'slug': 'cosmic-voyager',
            'description': 'Ultimate explorer - visit 100 locations',
            'category': 'EXPLORATION',
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 100,
            'tier': 5,
            'color': 'rainbow',
            'is_rare': True,
            'icon_path': '/badges/cosmic-voyager.png',
            'display_order': 6,
        },

        # ===================================================================
        # CONTRIBUTION BADGES (Location Adds)
        # ===================================================================
        {
            'name': 'Scout',
            'slug': 'scout',
            'description': 'Share your first discovery with the community',
            'category': 'CONTRIBUTION',
            'criteria_type': 'LOCATIONS_ADDED',
            'criteria_value': 1,
            'tier': 1,
            'color': 'bronze',
            'is_rare': False,
            'icon_path': '/badges/scout.png',
            'display_order': 1,
        },
        {
            'name': 'Discoverer',
            'slug': 'discoverer',
            'description': 'Expand the community map - add 5 locations',
            'category': 'CONTRIBUTION',
            'criteria_type': 'LOCATIONS_ADDED',
            'criteria_value': 5,
            'tier': 2,
            'color': 'silver',
            'is_rare': False,
            'icon_path': '/badges/discoverer.png',
            'display_order': 2,
        },
        {
            'name': 'Trailblazer',
            'slug': 'trailblazer',
            'description': 'Lead others to dark skies - add 10 locations',
            'category': 'CONTRIBUTION',
            'criteria_type': 'LOCATIONS_ADDED',
            'criteria_value': 10,
            'tier': 3,
            'color': 'gold',
            'is_rare': False,
            'icon_path': '/badges/trailblazer.png',
            'display_order': 3,
        },
        {
            'name': 'Location Legend',
            'slug': 'location-legend',
            'description': 'Prolific contributor - add 25 locations',
            'category': 'CONTRIBUTION',
            'criteria_type': 'LOCATIONS_ADDED',
            'criteria_value': 25,
            'tier': 4,
            'color': 'platinum',
            'is_rare': True,
            'icon_path': '/badges/location-legend.png',
            'display_order': 4,
        },

        # ===================================================================
        # REVIEW BADGES (Review Count)
        # ===================================================================
        {
            'name': 'Reviewer',
            'slug': 'reviewer',
            'description': 'Share your experiences - write 5 reviews',
            'category': 'REVIEW',
            'criteria_type': 'REVIEWS_WRITTEN',
            'criteria_value': 5,
            'tier': 1,
            'color': 'bronze',
            'is_rare': False,
            'icon_path': '/badges/reviewer.png',
            'display_order': 1,
        },
        {
            'name': 'Helpful Voice',
            'slug': 'helpful-voice',
            'description': 'Share detailed insights - write 10 reviews',
            'category': 'REVIEW',
            'criteria_type': 'REVIEWS_WRITTEN',
            'criteria_value': 10,
            'tier': 2,
            'color': 'silver',
            'is_rare': False,
            'icon_path': '/badges/helpful-voice.png',
            'display_order': 2,
        },
        {
            'name': 'Expert Reviewer',
            'slug': 'expert-reviewer',
            'description': 'Detailed, trusted opinions - write 25 reviews',
            'category': 'REVIEW',
            'criteria_type': 'REVIEWS_WRITTEN',
            'criteria_value': 25,
            'tier': 3,
            'color': 'gold',
            'is_rare': False,
            'icon_path': '/badges/expert-reviewer.png',
            'display_order': 3,
        },
        {
            'name': 'Trusted Critic',
            'slug': 'trusted-critic',
            'description': 'Authoritative voice - write 50 reviews',
            'category': 'REVIEW',
            'criteria_type': 'REVIEWS_WRITTEN',
            'criteria_value': 50,
            'tier': 4,
            'color': 'platinum',
            'is_rare': False,
            'icon_path': '/badges/trusted-critic.png',
            'display_order': 4,
        },
        {
            'name': 'Review Master',
            'slug': 'review-master',
            'description': 'Review legend - write 100 reviews',
            'category': 'REVIEW',
            'criteria_type': 'REVIEWS_WRITTEN',
            'criteria_value': 100,
            'tier': 5,
            'color': 'rainbow',
            'is_rare': True,
            'icon_path': '/badges/review-master.png',
            'display_order': 5,
        },

        # ===================================================================
        # COMMUNITY BADGES (Followers & Comments)
        # ===================================================================
        {
            'name': 'Conversationalist',
            'slug': 'conversationalist',
            'description': 'Engage with the community - comment on 10 reviews',
            'category': 'COMMUNITY',
            'criteria_type': 'COMMENTS_WRITTEN',
            'criteria_value': 10,
            'tier': 1,
            'color': 'bronze',
            'is_rare': False,
            'icon_path': '/badges/conversationalist.png',
            'display_order': 1,
        },
        {
            'name': 'Connector',
            'slug': 'connector',
            'description': 'Build your network - gain 10 followers',
            'category': 'COMMUNITY',
            'criteria_type': 'FOLLOWER_COUNT',
            'criteria_value': 10,
            'tier': 2,
            'color': 'silver',
            'is_rare': False,
            'icon_path': '/badges/connector.png',
            'display_order': 2,
        },
        {
            'name': 'Influencer',
            'slug': 'influencer',
            'description': 'Inspire other stargazers - gain 50 followers',
            'category': 'COMMUNITY',
            'criteria_type': 'FOLLOWER_COUNT',
            'criteria_value': 50,
            'tier': 3,
            'color': 'gold',
            'is_rare': False,
            'icon_path': '/badges/influencer.png',
            'display_order': 3,
        },
        {
            'name': 'Community Leader',
            'slug': 'community-leader',
            'description': 'Pillar of the community - gain 100 followers',
            'category': 'COMMUNITY',
            'criteria_type': 'FOLLOWER_COUNT',
            'criteria_value': 100,
            'tier': 4,
            'color': 'platinum',
            'is_rare': True,
            'icon_path': '/badges/community-leader.png',
            'display_order': 4,
        },

        # ===================================================================
        # SPECIAL BADGES (Advanced Achievements)
        # ===================================================================
        {
            'name': 'Photographer',
            'slug': 'photographer',
            'description': 'Capture the cosmos - upload 25 review photos',
            'category': 'SPECIAL',
            'criteria_type': 'SPECIAL_CONDITION',
            'criteria_value': 25,
            'tier': 3,
            'color': 'purple',
            'is_rare': True,
            'icon_path': '/badges/photographer.png',
            'display_order': 1,
        },
    ]

    # Bulk create badges
    Badge.objects.bulk_create([Badge(**badge_data) for badge_data in badges_to_create])


def reverse_seed_badges(apps, schema_editor):
    """Remove all seeded badges (for migration rollback)"""
    Badge = apps.get_model('starview_app', 'Badge')
    Badge.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0007_userprofile_pinned_badge_ids_badge_locationvisit_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_badges, reverse_seed_badges),
    ]
