# Generated by Django 5.1.13 on 2025-11-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0008_seed_initial_badges'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='badge',
            name='starview_ap_categor_373dbc_idx',
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['category', 'criteria_type', 'criteria_value'], name='badge_query_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['slug'], name='badge_slug_idx'),
        ),
    ]
