# Generated by Django 5.1.13 on 2025-11-12 07:20

from django.db import migrations


def add_missing_badges(apps, schema_editor):
    """
    Add the 4 missing badges that were not included in 0008_seed_initial_badges.py:
    - QUALITY category (3 badges)
    - TENURE category - Pioneer badge (1 badge)

    These badges exist in local dev but were missing from the original seeding migration.
    """
    Badge = apps.get_model('starview_app', 'Badge')

    badges_to_create = [
        # ===================================================================
        # QUALITY BADGES (Well-Rated Locations)
        # ===================================================================
        {
            'name': 'Quality Contributor',
            'slug': 'quality-contributor',
            'description': 'Share excellence - add 3 locations with 4+ star ratings',
            'category': 'QUALITY',
            'criteria_type': 'LOCATION_RATING',
            'criteria_value': 3,
            'tier': 1,
            'color': 'gold',
            'is_rare': False,
            'icon_path': '/badges/quality-contributor.png',
            'display_order': 1,
        },
        {
            'name': 'Trusted Source',
            'slug': 'trusted-source',
            'description': 'Reliable recommendations - add 5 locations with 4+ star ratings',
            'category': 'QUALITY',
            'criteria_type': 'LOCATION_RATING',
            'criteria_value': 5,
            'tier': 2,
            'color': 'silver',
            'is_rare': False,
            'icon_path': '/badges/trusted-source.png',
            'display_order': 2,
        },
        {
            'name': 'Elite Curator',
            'slug': 'elite-curator',
            'description': 'Master of quality - add 10 locations with 4+ star ratings',
            'category': 'QUALITY',
            'criteria_type': 'LOCATION_RATING',
            'criteria_value': 10,
            'tier': 3,
            'color': 'platinum',
            'is_rare': True,
            'icon_path': '/badges/elite-curator.png',
            'display_order': 3,
        },

        # ===================================================================
        # TENURE BADGES (Time-Based)
        # ===================================================================
        {
            'name': 'Pioneer',
            'slug': 'pioneer',
            'description': 'Early adopter - one of the first 100 verified users',
            'category': 'TENURE',
            'criteria_type': 'SPECIAL_CONDITION',
            'criteria_value': 100,
            'tier': 1,
            'color': 'legendary',
            'is_rare': True,
            'icon_path': '/badges/pioneer.png',
            'display_order': 1,
        },
    ]

    # Create badges only if they don't already exist (handles dev/prod sync)
    created_count = 0
    for badge_data in badges_to_create:
        badge, created = Badge.objects.get_or_create(
            slug=badge_data['slug'],
            defaults=badge_data
        )
        if created:
            created_count += 1

    print(f"Created {created_count} new badges (skipped {len(badges_to_create) - created_count} existing)")


def reverse_add_missing_badges(apps, schema_editor):
    """Remove the 4 badges added by this migration (for rollback)"""
    Badge = apps.get_model('starview_app', 'Badge')
    Badge.objects.filter(slug__in=[
        'quality-contributor',
        'trusted-source',
        'elite-curator',
        'pioneer',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0009_add_badge_indexes'),
    ]

    operations = [
        migrations.RunPython(add_missing_badges, reverse_add_missing_badges),
    ]
