# Generated by Django 5.1.13 on 2025-11-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0010_add_quality_and_pioneer_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['category', 'tier', 'display_order'], 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='emailsuppressionlist',
            options={'ordering': ['-added_date'], 'verbose_name': 'Email Suppression Entry', 'verbose_name_plural': 'Email Suppression List'},
        ),
        migrations.AlterModelOptions(
            name='favoritelocation',
            options={'verbose_name': 'Favorite Location', 'verbose_name_plural': 'Favorite Locations'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationvisit',
            options={'ordering': ['-visited_at'], 'verbose_name': 'Location Visit', 'verbose_name_plural': 'Location Visits'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Review Comment', 'verbose_name_plural': 'Review Comments'},
        ),
        migrations.AlterModelOptions(
            name='reviewphoto',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Review Photo', 'verbose_name_plural': 'Review Photos'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at'], 'verbose_name': 'User Badge', 'verbose_name_plural': 'User Badges'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='color',
        ),
    ]
