# Generated migration to update all badge definitions to current state
# This migration ensures production database matches development database

from django.db import migrations


def update_badge_definitions(apps, schema_editor):
    """
    Update all badge definitions with current values from development.
    This includes the new Ambassador badge and corrected tier/criteria values.
    """
    Badge = apps.get_model('starview_app', 'Badge')

    # Badge data from current development database
    badges_data = [
        {
            'slug': 'conversationalist',
            'name': 'Conversationalist',
            'description': 'Engage with the community - comment on 10 reviews',
            'category': 'COMMUNITY',
            'tier': 1,
            'criteria_type': 'COMMENTS_WRITTEN',
            'criteria_value': 10,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/conversationalist.png',
            'display_order': 1,
        },
        {
            'slug': 'connector',
            'name': 'Connector',
            'description': 'Build your network - gain 10 followers',
            'category': 'COMMUNITY',
            'tier': 2,
            'criteria_type': 'FOLLOWER_COUNT',
            'criteria_value': 10,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/connector.png',
            'display_order': 2,
        },
        {
            'slug': 'influencer',
            'name': 'Influencer',
            'description': 'Inspire other stargazers - gain 50 followers',
            'category': 'COMMUNITY',
            'tier': 3,
            'criteria_type': 'FOLLOWER_COUNT',
            'criteria_value': 50,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/influencer.png',
            'display_order': 3,
        },
        {
            'slug': 'community-leader',
            'name': 'Community Leader',
            'description': 'Pillar of the community - gain 100 followers',
            'category': 'COMMUNITY',
            'tier': 4,
            'criteria_type': 'FOLLOWER_COUNT',
            'criteria_value': 100,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/community-leader.png',
            'display_order': 4,
        },
        {
            'slug': 'ambassador',
            'name': 'Ambassador',
            'description': 'Beacon of the community - gain 200 followers',
            'category': 'COMMUNITY',
            'tier': 5,
            'criteria_type': 'FOLLOWER_COUNT',
            'criteria_value': 200,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/ambassador.png',
            'display_order': 5,
        },
        {
            'slug': 'scout',
            'name': 'Scout',
            'description': 'Share your first discovery with the community',
            'category': 'CONTRIBUTION',
            'tier': 1,
            'criteria_type': 'LOCATIONS_ADDED',
            'criteria_value': 1,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/scout.png',
            'display_order': 1,
        },
        {
            'slug': 'discoverer',
            'name': 'Discoverer',
            'description': 'Expand the community map - add 5 locations',
            'category': 'CONTRIBUTION',
            'tier': 2,
            'criteria_type': 'LOCATIONS_ADDED',
            'criteria_value': 5,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/discoverer.png',
            'display_order': 2,
        },
        {
            'slug': 'trailblazer',
            'name': 'Trailblazer',
            'description': 'Lead others to dark skies - add 10 locations',
            'category': 'CONTRIBUTION',
            'tier': 3,
            'criteria_type': 'LOCATIONS_ADDED',
            'criteria_value': 10,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/trailblazer.png',
            'display_order': 3,
        },
        {
            'slug': 'location-legend',
            'name': 'Location Legend',
            'description': 'Prolific contributor - add 25 locations',
            'category': 'CONTRIBUTION',
            'tier': 4,
            'criteria_type': 'LOCATIONS_ADDED',
            'criteria_value': 25,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/location-legend.png',
            'display_order': 4,
        },
        {
            'slug': 'first-light',
            'name': 'First Light',
            'description': 'Visit your first stargazing location',
            'category': 'EXPLORATION',
            'tier': 1,
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 1,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/first-light.png',
            'display_order': 1,
        },
        {
            'slug': 'explorer',
            'name': 'Explorer',
            'description': 'Begin your stargazing journey - visit 5 locations',
            'category': 'EXPLORATION',
            'tier': 2,
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 5,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/explorer.png',
            'display_order': 2,
        },
        {
            'slug': 'pathfinder',
            'name': 'Pathfinder',
            'description': 'Navigate the night sky - visit 10 locations',
            'category': 'EXPLORATION',
            'tier': 3,
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 10,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/pathfinder.png',
            'display_order': 3,
        },
        {
            'slug': 'stargazer',
            'name': 'Stargazer',
            'description': 'Dedicated night sky observer - visit 25 locations',
            'category': 'EXPLORATION',
            'tier': 4,
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 25,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/stargazer.png',
            'display_order': 4,
        },
        {
            'slug': 'celestial-navigator',
            'name': 'Celestial Navigator',
            'description': 'Master of dark skies - visit 50 locations',
            'category': 'EXPLORATION',
            'tier': 5,
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 50,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/celestial-navigator.png',
            'display_order': 5,
        },
        {
            'slug': 'cosmic-voyager',
            'name': 'Cosmic Voyager',
            'description': 'Ultimate explorer - visit 100 locations',
            'category': 'EXPLORATION',
            'tier': 5,
            'criteria_type': 'LOCATION_VISITS',
            'criteria_value': 100,
            'criteria_secondary': None,
            'is_rare': True,
            'icon_path': '/badges/cosmic-voyager.png',
            'display_order': 6,
        },
        {
            'slug': 'quality-contributor',
            'name': 'Quality Contributor',
            'description': 'Share excellence - add 3 locations with 4+ star ratings',
            'category': 'QUALITY',
            'tier': 1,
            'criteria_type': 'LOCATION_RATING',
            'criteria_value': 3,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/quality-contributor.png',
            'display_order': 1,
        },
        {
            'slug': 'trusted-source',
            'name': 'Trusted Source',
            'description': 'Reliable recommendations - add 6 locations with 4+ star ratings',
            'category': 'QUALITY',
            'tier': 2,
            'criteria_type': 'LOCATION_RATING',
            'criteria_value': 6,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/trusted-source.png',
            'display_order': 2,
        },
        {
            'slug': 'stellar-curator',
            'name': 'Stellar Curator',
            'description': 'Curate the best - add 12 locations with 4+ star ratings',
            'category': 'QUALITY',
            'tier': 3,
            'criteria_type': 'LOCATION_RATING',
            'criteria_value': 12,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/stellar-curator.png',
            'display_order': 3,
        },
        {
            'slug': 'elite-curator',
            'name': 'Elite Curator',
            'description': 'Master of quality - add 24 locations with 4+ star ratings',
            'category': 'QUALITY',
            'tier': 4,
            'criteria_type': 'LOCATION_RATING',
            'criteria_value': 24,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/elite-curator.png',
            'display_order': 4,
        },
        {
            'slug': 'reviewer',
            'name': 'Reviewer',
            'description': 'Share your experiences - write 5 reviews',
            'category': 'REVIEW',
            'tier': 1,
            'criteria_type': 'REVIEWS_WRITTEN',
            'criteria_value': 5,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/reviewer.png',
            'display_order': 1,
        },
        {
            'slug': 'helpful-voice',
            'name': 'Helpful Voice',
            'description': '10 upvotes received on your reviews',
            'category': 'REVIEW',
            'tier': 2,
            'criteria_type': 'UPVOTES_RECEIVED',
            'criteria_value': 10,
            'criteria_secondary': None,
            'is_rare': False,
            'icon_path': '/badges/helpful-voice.png',
            'display_order': 2,
        },
        {
            'slug': 'expert-reviewer',
            'name': 'Expert Reviewer',
            'description': '25 reviews with 75%+ helpful ratio',
            'category': 'REVIEW',
            'tier': 3,
            'criteria_type': 'HELPFUL_RATIO',
            'criteria_value': 25,
            'criteria_secondary': 75,
            'is_rare': False,
            'icon_path': '/badges/expert-reviewer.png',
            'display_order': 3,
        },
        {
            'slug': 'trusted-critic',
            'name': 'Trusted Critic',
            'description': '50 reviews with 80%+ helpful ratio',
            'category': 'REVIEW',
            'tier': 4,
            'criteria_type': 'HELPFUL_RATIO',
            'criteria_value': 50,
            'criteria_secondary': 80,
            'is_rare': False,
            'icon_path': '/badges/trusted-critic.png',
            'display_order': 4,
        },
        {
            'slug': 'review-master',
            'name': 'Review Master',
            'description': '100 reviews with 85%+ helpful ratio',
            'category': 'REVIEW',
            'tier': 5,
            'criteria_type': 'HELPFUL_RATIO',
            'criteria_value': 100,
            'criteria_secondary': 85,
            'is_rare': False,
            'icon_path': '/badges/review-master.png',
            'display_order': 5,
        },
        {
            'slug': 'photographer',
            'name': 'Photographer',
            'description': 'Capture the cosmos - upload 25 review photos',
            'category': 'SPECIAL',
            'tier': 1,
            'criteria_type': 'SPECIAL_CONDITION',
            'criteria_value': 25,
            'criteria_secondary': None,
            'is_rare': True,
            'icon_path': '/badges/photographer.png',
            'display_order': 1,
        },
        {
            'slug': 'pioneer',
            'name': 'Pioneer',
            'description': 'Early adopter - one of the first 100 verified users',
            'category': 'TENURE',
            'tier': 1,
            'criteria_type': 'SPECIAL_CONDITION',
            'criteria_value': 100,
            'criteria_secondary': None,
            'is_rare': True,
            'icon_path': '/badges/pioneer.png',
            'display_order': 1,
        },
    ]

    # Update or create each badge
    for badge_data in badges_data:
        Badge.objects.update_or_create(
            slug=badge_data['slug'],
            defaults=badge_data
        )


def reverse_update(apps, schema_editor):
    """
    Reverse operation - not implemented as this would lose data.
    If you need to revert, restore from database backup.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0011_remove_badge_color_field'),
    ]

    operations = [
        migrations.RunPython(update_badge_definitions, reverse_update),
    ]
